### ISSUE TITLE
HiDPI supoort

### ISSUE THREAD

**Issue by youngkaneda** [supermariofps/hatsune-miku-windows-linux-cursors#3]
There is any chance of the icons having HiDPI support? my laptop screen is too big (2560x1600) so I scale up its dpi through .Xresources. But when I try to change the Xcursor sizes, the miku icon set dont follows up.

Currently I'm using Arch Linux, with HerbstluftWM as window manager.

**Comment by supermariofps** [comment]
Hello! Sorry for taking so long to answer, I have been busy with a few personal things, but I'll be working on it in the next few days, hope it didn't take much longer!

**Comment by youngkaneda** [comment]
No problem, thx for the attention, I could work on it and send a pull request, but I know nothing about cursors creation haha

**Comment by supermariofps** [comment]
np! I've been looking for how I could up-scale the cursors but it always got blurry, I'm not sure if I'll be able to make it with a good quality but, I'll keep looking for a better way to do it.

**Comment by youngkaneda** [comment]
I think maybe if tou vectorize the cursor images you can scale them as much as you want, but I don't know if cursors works with vectors or only images

**Comment by toydotgame** [comment]
I'm pretty sure X cursors can only be raster (at least afaik)

**Comment by supermariofps** [comment]
Hello! I was without my PC for the past few days bc of a problem with my power supply.

After getting a new power supply and finally being able to use my PC again, one of the solutions I found for the cursors was extracting each frame and up-scaling it one by one, but that would be _lot_ of work since I will need to redo each animation frame by frame so, not sure if I will be able to make the HiDPI support so soon, I'll keep looking for a better way to do it but, not sure when I'll be able to, sorry about that.

also, the way I'm handling the cursors is using the [RW Cursor editor](http://www.rw-designer.com/cursor-maker) on windows since it's easier to edit and it support exporting for both OS instead of using Xcursors.

**Comment by 4e554c4c** [comment]
This sounds pretty easy to do in a shell script using xcur2png and xcursorgen. I'll try to take a look at it this weekend.
